### ISSUE TITLE
Feature Request: Confgurable backups

### ISSUE THREAD

**Issue by vxfemboy** [vxfemboy/backup-webapp#2]
Currently, the automated backups are hardcoded to run on the first day of every month at midnight. To enhance the flexibility and usability of the backup system, we should add configurability for the automated backup schedule in the `config.toml` file.

#### Enhancement Details:
1. **Add New Configuration Options:**
   - Introduce new configuration options in the `config.toml` file to specify the cron schedule for automated backups.
   - Example:
     ```toml
     [backup]
     dirs = [
         "/path/to/project1",
         "/path/to/project2",
     ]                            # Directories to backup
     storage_path = "./backups/"  # Path to store backup files
     backup_prefix = "backup"     # Prefix for backup filenames
     cron_schedule = "0 0 1 * *"  # Cron schedule for automated backups
     ```

2. **Update Configuration Struct:**
   - Update the `Config` struct in `main.go` to include the new `cron_schedule` field.
   - Example:
     ```go
     type Config struct {
         // ... other fields ...
         Backup struct {
             Dirs         []string `toml:"dirs"`
             StoragePath  string   `toml:"storage_path"`
             BackupPrefix string   `toml:"backup_prefix"`
             CronSchedule string   `toml:"cron_schedule"`
         } `toml:"backup"`
         // ... other fields ...
     }
     ```

3. **Modify Cron Job Setup:**
   - Modify the cron job setup in the `main` function to use the configured cron schedule.
   - Example:
     ```go
         // Setup cron for automated backups
         c := cron.New()
         cronSchedule := config.Backup.CronSchedule
         // ... other code ...
     }
     ```
